### PR TITLE
extremely important PR

### PR DESCRIPTION
**Pull request by weddleben**
you are welcome

### CODE REVIEW

**Comment by VictoriqueMoe** [comment]
I don't understand this PR except for fixing `aria-selected`

**Comment by weddleben** [comment]
> I don't understand this PR except for fixing `aria-selected`

the way GH displays the diff is weird. i didn't change `aria-selected`. i fixed the order of the examples

ss

**Comment by VictoriqueMoe** [comment]
what is the order?

**Comment by weddleben** [comment]
> what is the order?

you:
ss


me:
ss2

I already talked to @nakedmcse and he agrees

**Comment by VictoriqueMoe** [comment]
what is the logic in your order?

**Comment by nakedmcse** [comment]
**> I already talked to @nakedmcse and he agrees**

No the hell you did not 👎

**Comment by weddleben** [comment]
> what is the logic in your order?

language popularity/use

**Comment by VictoriqueMoe** [comment]
> > what is the logic in your order?
> 
> language popularity/use

citation required

**Comment by VictoriqueMoe** [comment]
closing due to cringe

**Comment by weddleben** [comment]
> > > what is the logic in your order?
> > 
> > 
> > language popularity/use
> 
> citation required

https://www.tiobe.com/tiobe-index/
ss

**Comment by VictoriqueMoe** [comment]
> > > > what is the logic in your order?
> > > 
> > > 
> > > language popularity/use
> > 
> > 
> > citation required
> 
> https://www.tiobe.com/tiobe-index/ ss

fake and gay

**Comment by weddleben** [comment]
i have amazing powers of prediction

ss

**Pull request closed without merging**
